version: "3.9"

services:

  camrecv:
    build:
      dockerfile: ./Dockerfile
    restart: always
    network_mode: host

  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./conf:/conf
    command: /conf/mediamtx.yml
